### ISSUE TITLE
Audio is only recorded through the microphone on the device, not through the microphone of the bluetooth headset (Android)

### ISSUE THREAD

**Issue by vietdung97** [AgoraIO-Extensions/react-native-agora#420] opened 2021-10-05 08:36 UTC
Hi dev team, my audio is only recorded through the microphone on the device, not through the microphone of the bluetooth headset (Android). Is there a way to record audio through the headset's mic?

**Comment by Saehanseul** [comment] 2021-10-13 02:28
ios is problem like this too. will be fix next version android & ios both?

**Comment by angelorobo** [comment] 2022-02-17 19:21
We're using Flutter and also see this issue. Have this issue solved yet?

**Comment by oelerpearler** [comment] 2022-12-08 14:06
Since this issue is a duplicate of another issue (or vice versa) https://github.com/AgoraIO-Extensions/react-native-agora/issues/507 I quickly wanted to point to the relveant comment that describes the solution for the issue: https://github.com/AgoraIO-Extensions/react-native-agora/issues/507#issuecomment-1342754091

**Closed** 2023-03-25 21:58 UTC
Labels: wontfix
